### ISSUE TITLE
rocky.github.com -> rocky.github.io?

### ISSUE THREAD

**Issue by sogaiu** [rocky/rocky.github.com#1]
Hi,

Currently, at least one of the links shown when visiting this repository:

![rocky](https://user-images.githubusercontent.com/33044872/214311208-8a0df6b0-6f80-41c0-9222-99b73dcaca84.png)

leads to a 404 page:

![404](https://user-images.githubusercontent.com/33044872/214311458-dd1d9c59-ab9b-45b3-84c2-7b2131fd7e95.png)

May be that is not intended?

**Comment by rocky** [comment]
All occurances of rocky.github.com have been replaced by rocky.github.io. (When these were written, rocky.github.io didn't exist and you _had_ to use rocky.github.com).

**Comment by sogaiu** [comment]
Aha, thanks for the explanation and quick update.
